### ISSUE TITLE
erroare 1

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#15]
pentru prima data vad o eroare cind incerc sa schimb pe un alt canal din ghid epg;
dupa reboot este ok:
```
2020-06-04 23:20:37.571 T:3010816480  NOTICE: Whitelist search for: width: 1024, height: 576, fps: 25.000, 3D: false
2020-06-04 23:20:37.575 T:3010816480  NOTICE: Display resolution ADJUST : 1920x1080 @ 60.000000 Hz (27) (weight: 0.033)
2020-06-04 23:21:05.619 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:21:30.405 T:3010816480  NOTICE: Whitelist search for: width: 1024, height: 576, fps: 25.000, 3D: false
2020-06-04 23:21:30.410 T:3010816480  NOTICE: Display resolution ADJUST : 1920x1080 @ 60.000000 Hz (27) (weight: 0.034)
2020-06-04 23:21:32.212 T:3010816480  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.iptvsimple_89740685.pvr
2020-06-04 23:21:32.291 T:2545939296  NOTICE: Creating InputStream
2020-06-04 23:21:32.540 T:2545939296  NOTICE: Creating Demuxer
2020-06-04 23:21:32.541 T:2545939296  NOTICE: Opening stream: 1001 source: 256
2020-06-04 23:21:32.961 T:2545939296  NOTICE: Whitelist search for: width: 1024, height: 576, fps: 25.000, 3D: false
2020-06-04 23:21:32.963 T:2545939296  NOTICE: Display resolution ADJUST : 1920x1080 @ 60.000000 Hz (27) (weight: 0.000)
2020-06-04 23:21:32.976 T:2545939296  NOTICE: Creating video codec with codec id: 27
2020-06-04 23:21:32.977 T:3010816480  NOTICE: Whitelist search for: width: 1024, height: 576, fps: 25.000, 3D: false
2020-06-04 23:21:32.979 T:3010816480  NOTICE: Display resolution ADJUST : 1920x1080 @ 60.000000 Hz (27) (weight: 0.017)
2020-06-04 23:21:32.984 T:2545939296  NOTICE: Opening stream: 1002 source: 256
2020-06-04 23:21:32.984 T:2545939296  NOTICE: Finding audio codec for: 86018
2020-06-04 23:21:32.985 T:2545939296  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-06-04 23:21:33.594 T:2455036768  NOTICE: Previous line repeats 1 times.
2020-06-04 23:21:33.594 T:2455036768 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-06-04 23:22:05.641 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:30:03.816 T:2455036768   ERROR: Previous line repeats 7 times.
2020-06-04 23:30:03.816 T:2455036768 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-06-04 23:30:05.824 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:30:58.311 T:3010816480  NOTICE: Whitelist search for: width: 1024, height: 576, fps: 25.000, 3D: false
2020-06-04 23:30:58.319 T:3010816480  NOTICE: Display resolution ADJUST : 1920x1080 @ 60.000000 Hz (27) (weight: 0.049)
2020-06-04 23:31:05.843 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:32:21.573 T:2990576480   ERROR: Previous line repeats 1 times.
2020-06-04 23:32:21.573 T:2990576480 WARNING: ActiveAE - large audio sync error: -89442.330954
2020-06-04 23:32:25.611 T:2990576480 WARNING: ActiveAE - large audio sync error: -89384.991395
2020-06-04 23:33:05.887 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:33:33.119 T:2463429472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 591, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 566, in router
                                                play_video(params['channel_endpoint'], params['channel_metadata'])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 380, in play_video
                                                _stream_data_ = json.loads(_request_.content)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-06-04 23:33:48.762 T:3010816480  NOTICE: CVideoPlayer::CloseFile()
2020-06-04 23:33:48.769 T:2545939296  NOTICE: CVideoPlayer::OnExit()
2020-06-04 23:33:48.770 T:2545939296  NOTICE: Closing stream player 1
2020-06-04 23:33:48.770 T:2545939296  NOTICE: Waiting for audio thread to exit
2020-06-04 23:33:48.802 T:2402583392  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-06-04 23:33:48.803 T:2545939296  NOTICE: Closing audio device
2020-06-04 23:33:48.815 T:3010816480  NOTICE: VideoPlayer: waiting for threads to exit
2020-06-04 23:33:48.853 T:2545939296  NOTICE: Deleting audio codec
2020-06-04 23:33:48.853 T:2545939296  NOTICE: Closing stream player 2
2020-06-04 23:33:48.854 T:2545939296  NOTICE: waiting for video thread to exit
2020-06-04 23:33:48.897 T:2455036768  NOTICE: thread end: video_thread
2020-06-04 23:33:48.899 T:2545939296  NOTICE: deleting video codec
2020-06-04 23:33:48.910 T:3010816480  NOTICE: VideoPlayer: finished waiting
2020-06-04 23:33:48.911 T:3010816480  NOTICE: CVideoPlayer::CloseFile()
2020-06-04 23:33:48.911 T:3010816480  NOTICE: VideoPlayer: waiting for threads to exit
2020-06-04 23:33:48.911 T:3010816480  NOTICE: VideoPlayer: finished waiting
2020-06-04 23:33:50.425 T:2634019680  NOTICE: AddOnLog: PVR IPTV Simple Client: LoadEPG EPG Loaded - 86 (ms)
2020-06-04 23:34:05.906 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:35:38.126 T:3010816480   ERROR: Previous line repeats 1 times.
2020-06-04 23:35:38.126 T:3010816480  NOTICE: Samba is idle. Closing the remaining connections
2020-06-04 23:36:05.942 T:2761724768   ERROR: INFO:schedule:Running job Job(interval=1, unit=minutes, do=schedule_jobs, args=(), kwargs={})
2020-06-04 23:37:13.334 T:3010816480   ERROR: Previous line repeats 1 times.
2020-06-04 23:37:13.334 T:3010816480   ERROR: CPythonInvoker(87, /storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py): script didn't stop in 5 seconds - let's kill it
2020-06-04 23:37:46.442 T:2534404960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 591, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 566, in router
                                                play_video(params['channel_endpoint'], params['channel_metadata'])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 380, in play_video
                                                _stream_data_ = json.loads(_request_.content)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-06-04 23:37:58.707 T:3010816480   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-06-04 23:38:04.446 T:2410976096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 591, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 563, in router
                                                list_channels(params['category'])
                                              File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 250, in list_channels
                                                _ch_epg_data_ = json.loads(functions.get_cached_epg_data(_ch_metadata_['new-info']['meta']['streamId'], vars.__AddonID__, vars.__AddonSession__, MyAddon_DataDir))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

```

**Comment by cralin** [comment]
Ce versiune de add-on folosesti ?
Care e secventa de pasi care o faci pina ajungi la problema si la eroarea
din log-uri ?
Ce scrie in "plugin.vodeo.DigiOnline.log" dupa ce ai activat debug logging
si ai replicat problema ?

**Comment by rapi3** [comment]
Folosesc ultima versiune.
Inca nu am putut replica problema si aseara cand s-a intimplat eram prea adormit ca sa ma mai duc la calculator sa intru pe ssh sa vad exact log-ul asa ca i-am dat restart la kodi si dupa ce am vazut ca merge m-am culcat.
Astazi dimineata am sesizat ca log-ul addonului este suprascris la repornire asa ca nu mai era nimic in el de ieri.
